# Generated by Django 6.0.2 on 2026-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetholding',
            name='asset_type',
            field=models.CharField(choices=[('equity', 'Equity'), ('crypto', 'Crypto'), ('commodity', 'Commodity'), ('real_estate', 'Real Estate'), ('private_equity', 'Private Equity'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
